# Generated by Django 3.1.3 on 2022-02-03 18:55

from django.db import migrations, models
import django.utils.timezone
import utility.path
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipe_item',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recipe_item_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('recipe_name', models.CharField(max_length=255)),
                ('recipe_ingredients', models.TextField(blank=True, null=True)),
                ('recipe_instructions', models.TextField(blank=True, null=True)),
                ('recipe_photo', models.ImageField(null=True, upload_to=utility.path.recipe_image_path)),
                ('recipe_items', models.ManyToManyField(blank=True, to='database.recipe_item')),
            ],
        ),
    ]
